### ISSUE TITLE
操作求助

### ISSUE THREAD

**Issue by sleepyheadforu** [wintertee/Smartisan-notes-downloader#1]
请问一定要是 Chrome 浏览器吗？**edge 可以吗**？，（因为我常听说内核一致）Chrome driver 软件我没听说过，我**大胆揣测**这个软件是刚需，您是出于在 edge 实现比较复杂，这般考虑吗，请问您**后续会开发edge**吗？
我作为小白，**具体操作**，还是有些迷茫 **咋弄那个requirement**？[发呆]

**谢谢您的付出！**

**Comment by wintertee** [comment]
你好！

Edge浏览器也基于Chromium内核，所以理论上这个程序也适用于Edge，但需要稍加修改。

首先，你应当[下载本仓库](https://github.com/wintertee/Smartisan-notes-downloader/archive/refs/heads/main.zip)并解压。

然后，[下载 Microsoft Edge WebDriver](https://learn.microsoft.com/zh-cn/microsoft-edge/webdriver-chromium/?tabs=python#download-microsoft-edge-webdriver)，并把它放在本仓库的根目录下。

然后对代码进行对应的修改（我没有测试过）：

把 `main.py` [第41行](https://github.com/wintertee/Smartisan-notes-downloader/blob/2265cee53792755649aa0144918cf6a29907c0c2/main.py#L41)开始的

```python3
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--incognito")


driver = webdriver.Chrome(chrome_options=chrome_options)
```

修改为

```python3
chrome_options = webdriver.edge.options.Options()
chrome_options.add_argument("--incognito")

driver = webdriver.Edge(chrome_options=chrome_options)
```

最后在本仓库的根目录下打开命令行：

安装依赖: `pip install -r requirements.txt`

运行程序：`python main.py`
