### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by jerryfan86** [wintertee/Smartisan-notes-downloader#2]
代码可以运行但一堆小问题，环境搭建时pip install -r requirements.txt执行命令时 requirements.txt文件格式是anaconda导出格式。使用pip安装不了这些包。我是修改了 requirements.txt文件内容才成功的。

脚本运行起来，保存的便签文件名字过长就退出了。如下：
Traceback (most recent call last):
  File "D:\download\Compressed\Smartisan-notes-downloader-main\main.py", line 190, in <module>
    with open(os.path.join(subdir, filename), "w", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'downloads\\1683255264\\20200929_宝贝来列假的时候注意少碰点冷水也不要洗头发如果非要洗那么洗完头一定要立即吹干晚上记得时睡觉按时吃饭回家了半躺着把手搓热在小腹上顺时针揉揉想它流出来你就平躺着不想.md\\20200929_宝贝来列假的时候注意少碰点冷水也不要洗头发如果非要洗那么洗完头一定要立即吹干晚上记得时睡觉按时吃饭回家了半躺着把手搓热在小腹上顺时针揉揉想它流出来你就平躺着不想.md'

**Comment by jerryfan86** [comment]
都是小问题，我已经成功导出所有便签了。感谢开源

**Comment by wintertee** [comment]
谢谢反馈。欢迎提交PR修复错误！
