### ISSUE TITLE
非常感谢！在 ChatGPT 的帮助下，改了 requirements.txt 中的=为==，就顺利运行了

### ISSUE THREAD

**Issue by zhy0123** [wintertee/Smartisan-notes-downloader#3]
一开始运行报错，在 ChatGPT 的提示下，将安装 requirements.txt 改为在命令行环境中分别执行了如下命令：
`pip3 install selenium==4.5.0`
`pip3 install selenium-wire==5.1.0`
`pip3 install pyyaml==6.0`
然后再执行：
`python3 main.py`
就顺利运行了。

**Comment by wintertee** [comment]
谢谢反馈
